Traveling Salesman Problem using Random-restart Hill Climbing
=============================================================

Uses random-restart hill climbing for finding a solution to the traveling salesman problem. Assumes a complete graph. Starts by choosing a random configuration of nodes; neighbours of a given state are generated by selecting a random node within the current state and swapping the position of that node with the other nodes.

"Cities.txt" contains test data for the problem. The threshold between two subsequent descends (which is passed as a parameter to the hill climbing method) determines the optimality of the solution found.

Code written in Python 2.7.4.
